//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormGiris.cs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fis()
        {
            this.FisDetay = new HashSet<FisDetay>();
        }
    
        public int Id { get; set; }
        public string FisKodu { get; set; }
        public string Cari { get; set; }
        public string OdemeTuru { get; set; }
        public System.DateTime Tarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FisDetay> FisDetay { get; set; }
    }
}
