//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormGiris.cs
{
    using System;
    using System.Collections.Generic;
    
    public partial class FisAll
    {
        public int Id { get; set; }
        public string FisKodu { get; set; }
        public string Cari { get; set; }
        public string OdemeTuru { get; set; }
        public System.DateTime Tarih { get; set; }
        public string UrunKodu { get; set; }
        public string UrunAdi { get; set; }
        public decimal Miktar { get; set; }
        public decimal BirimFiyat { get; set; }
        public decimal Kdv { get; set; }
        public Nullable<decimal> Toplam { get; set; }
    }
}
