//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormGiris.cs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MuhasebeDBEntities2 : DbContext
    {
        public MuhasebeDBEntities2()
            : base("name=MuhasebeDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CariKart> CariKart { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<StokKart> StokKart { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<SatisFatura> SatisFatura { get; set; }
        public virtual DbSet<FisAll> FisAll { get; set; }
    }
}
