//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormGiris.cs
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokKart
    {
        public int Id { get; set; }
        public string StokKodu { get; set; }
        public string StokAdi { get; set; }
        public string Birim { get; set; }
        public string Barkod { get; set; }
        public Nullable<decimal> KDV { get; set; }
        public string Aciklama { get; set; }
    }
}
