//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormGiris.cs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        public int Id { get; set; }
        public string Kodu { get; set; }
        public string Adi { get; set; }
        public int Miktar { get; set; }
        public decimal BirimFiyat { get; set; }
    }
}
